### ISSUE TITLE
More descriptive 403 error messages

### ISSUE THREAD

**Issue by ekerstein** [florimondmanca/djangorestframework-api-key#146]
When an API key is revoked or expired I get this response with a 403 error:
```
    "detail": "You do not have permission to perform this action."
```
Is there a way to provide a more descriptive error message, such as "API key is expired"? The reason I ask is because for my application API keys automatically expire after 60 days. I need the user to know that somehow. 

What are the best practices for this kind of use case? Thanks!

**Comment by florimondmanca** [comment]
Hi @ekerstein 

Doing some cleanup around here. Briefly, I believe this message comes from a default Django REST Framework behavior. I assume there should be some info in the DRF docs about how to customize error messages — and perhaps you can apply that to customized permission classes.

In the meantime I'll close this, but happy to discuss any solutions you may have found since then. :-)

Thanks
