### ISSUE TITLE
Security link broken in readme

### ISSUE THREAD

**Issue by aripap** [florimondmanca/djangorestframework-api-key#152]
**Describe the bug**
The link in readme is to `blob/master/security.md#caveats` it should be to `doc/security.md#caveats`

**To Reproduce**
Click the link LOL.

**Comment by florimondmanca** [comment]
@aripap Hi,

> Click the link LOL.

Doesn't come across very cordial to readers or people that would like to help — or to me personally.

If the link's broken, then by all means be the change and consider submitting a pull request.

I'll close this for now because I don't think this kind of behavior is acceptable around here — but still happy to review any contribution to fix said broken link.

Thanks
