### ISSUE TITLE
request always return unvalid credentials when adding HasAPIkey to permissions_classes

### ISSUE THREAD

**Issue by souheyltoumi** [florimondmanca/djangorestframework-api-key#155]
**Describe the bug**
request always return unvalid credentials when adding HasAPIkey to permissions_classes
**To Reproduce**
1. create a simple class
from rest_framework_api_key.permissions import HasAPIKey

class ProjectListView(APIView):

    permission_classes = (HasAPIKey,)

    def get(self, request):
        """Retrieve a project based on the request API key."""
        return HttpResponse("SUCCESS")
2. Configure urls 
3.generate apikey
4.at postman configure the header as its stated in the user guide 
5.when accessing that Url we get unvalid credentials

**Expected behavior**
expect to get the result success
**Screenshots**
![image](https://user-images.githubusercontent.com/56138763/101208803-ffc1e180-3672-11eb-82cc-7d1341ee6192.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: [e.g. 0.2.2]
 - Python Version: [e.g. 3.7]
 - Django Version: [e.g. 2.1]
 - DRF Version: [e.g. 3.8.2]

**Additional context**

**Comment by jrujano** [comment]
The problem comes from the **verify** function of the crypto.py file

**Comment by florimondmanca** [comment]
@souheyltoumi Hello!

From that Postman screenshot it seems you're setting Authorization in query parameters, but it should be set in the Headers section. This is because HasAPIKey looks for the API key in the Authorization header by default.

If you need to use query petals then I believe there are sufficient instructions in the docs for how to do that: [API Key parsing](https://florimondmanca.github.io/djangorestframework-api-key/guide/#api-key-parsing) (the docs show how to get the API key from a cookie instead, but you you want to read it from query parameters that would be the same place.)

I'm going to treat that as resolved for now but if this doesn't do the trick, feel free to reach back!

Thanks
