### ISSUE TITLE
`HasAPIKey` adds huge performance (speed) hit

### ISSUE THREAD

**Issue by jorgenbuilder** [florimondmanca/djangorestframework-api-key#173]
I'm seeing a huge performance hit when adding the `HasAPIKey` permission class. I've isolated it down to toggling the following setting:

```python
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [],
    # 'DEFAULT_PERMISSION_CLASSES': ['rest_framework_api_key.permissions.HasAPIKey'],
}
```

Which gives the following results:

```bash
# Without API Keys

Testing Resource #1...
	Done in 0.09s

Testing Resource #2...
	Avg after 10 attempts: 0.35s

Testing Resource #3...
	Avg after 10 attempts: 0.11s
```

```bash
# With HasAPIKey

Testing Resource #1...
	Done in 0.55s

Testing Resource #2...
	Avg after 10 attempts: 0.83s

Testing Resource #3...
	Avg after 10 attempts: 0.46s
```

I wasn't able to find any similar tickets. Has anyone seen this behaviour before?

**Comment by florimondmanca** [comment]
Hello,

Thanks for putting this up.

Some questions for consideration:

* What's the scale of your situation? (Eg dealing with 10 API keys versus 10,000)
* Is it an usual or unusual situation for Django permissions to cause performance reductions like this? Eg is this visible with regular user-based permissions?
* If so, do people deal with this in general?
* If not, maybe the DB query performed in our case is unoptimal, and we'd need to dig in to find out more.

**Comment by timsluis** [comment]
I'm seeing the same behaviour, a more or less 5x performance drop. Scale: just a few API keys.

**Comment by hyzyla** [comment]
I have the same problem. Memory profiler [silk](https://github.com/jazzband/django-silk) gives hint that problem is related with cryptography


```python
from silk.profiling.profiler import silk_profile

class TerritoryAPIPermission(HasAPIKey):

    @silk_profile(name='TerritoryAPIPermission.has_permission')
    def has_permission(self, request: HttpRequest, view: APIView) -> bool:

        # always allow performing request when browsable api rendered is selected
        renderer = getattr(request, 'accepted_renderer', None)
        if isinstance(renderer, BrowsableAPIRenderer):
            return True

        # in other cases verify API token
        return super().has_permission(request, view)
```

![image](https://user-images.githubusercontent.com/7952949/145986106-745464a2-8f42-428e-871d-924ee30576cc.png)

![image](https://user-images.githubusercontent.com/7952949/145986423-95f6a1b2-a2af-4a09-8153-60b4f99d7a80.png)

**Comment by hyzyla** [comment]
So, one for improving performance of key verification, you can tweak PASSWORD_HASHERS for using different hash method. 

https://security.stackexchange.com/questions/246062/pbkdf2-usage-will-slow-rest-api-down

 https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-PASSWORD_HASHERS

**Comment by florimondmanca** [comment]
It's possible about half of the effect could come from #150, which likely results in performing the API key checking twice in most cases.

**Comment by florimondmanca** [comment]
I did some basic benchmarking on my end using the `test_project` in this repo (slightly edited to add a `/` route), and this script:

```python
import httpx
import statistics

api_key = "<Enter Hero API key created through test_project admin>"


def api_key_auth(request: httpx.Request) -> httpx.Request:
    request.headers["Authorization"] = f"Api-Key {api_key}"
    return request


times = []

with httpx.Client() as client:
    for _ in range(10):
        response = client.get("http://localhost:8000", auth=api_key_auth)
        times.append(response.elapsed.total_seconds())

m = statistics.mean(times)
s = statistics.stdev(times)

print(f"{m=:.3f} seconds ({s=:.3f} seconds)")
```

Results:

* Argon2: 0.197, std=0.040
* PBKDF2: 0.363, std=0.093
* BcryptSHA256: 0.425, std=0.050

So, results are indeed slightly better when using Argon2 instead of the default PBKDF2 hasher (i.e. placing Argon2 higher in `PASSWORD_HASHERS`).

To perform this

**Comment by davidfischer** [comment]
These password hashers are slow (very roughly ~100ms+) by design to prevent brute forcing. However, #150 isn't the only place where the hasher is called a second time. Something like the guide's recommendation for getting the API key in the view will also hash the key again: https://github.com/florimondmanca/djangorestframework-api-key/blob/4984a143cd0db179c1335bb8562909de42d60b8f/docs/guide.md?plain=1#L162-L166

`HasAPIKey` should probably cache the key somehow (on the request?) if the permission check is successful.

**Comment by florimondmanca** [comment]
Right. Everything that calls `api_key.is_valid(...)` will trigger a hash computation and result in the added latency.

I'm a bit far from Django now. Is there an idiomatic way in Django for permission classes to make data available to requests? Like a "state" on the request?

**Comment by davidfischer** [comment]
If you're sure that the key has already been checked, worst case you can just do a database lookup by `prefix` which will be much faster than re-hashing.

> Is there an idiomatic way in Django for permission classes to make data available to requests? Like a "state" on the request?

I wouldn't say there's one way to do this. Probably the simplest would be to set `request.api_key` or you could use a thread local or something like that.

**Comment by davidfischer** [comment]
> I think there's a meaningful discussion to have on whether that "hash API keys so they aren't readable in the database" idea was a good one.

The more I think about this, the more I think this is the real question we should be answering and I think using a much faster hasher is probably the answer. The purpose of very slow password hashers is to protect the passwords if the database leaks somehow. These hashers will make brute forcing any passwords from the hash much more costly. However, this module is generating those keys randomly and the secret part not stored in the DB is 32 alphanumeric characters long (62^32 ~= 190 bits of entropy). That's too much entropy to be brute forced or precomputed.

As a result, you could probably just use sha256 or sha512 on the generated key. That would drastically mitigate the performance hit and reversing one of those hashes to a 190bit key should be impossible (famous last words). That might remove the need for caching the key on the request. For reference, [django-rest-knox](https://github.com/James1345/django-rest-knox/blob/3a1bc584f9691f4bc19d8a04a98c68c293be9ca6/knox/settings.py#L10), a similar module but it ties keys to users, is just using sha512 on the generated key and storing it.

**Comment by florimondmanca** [comment]
@davidfischer Now, that is a _great_ point. At the level of entropy of our randomly generated secret keys, even a regular SHA hash algorithm would do the trick as far as preventing access to the secret keys from someone with access to the database is concerned.

So, it looks like switching hashers could resolve this issue…

The remaining questions to figure out are:

- How much of a performance boost can we expect (do some tests)
- How to ensure hashes are properly migrated. Do we just switch the hasher, issue a new release and Django will magically upgrade hashes? Or do we need something else either from us, or from users with extra docs?

**Comment by davidfischer** [comment]
> * How much of a performance boost can we expect (some testing would be appropriate)

Testing is appropriate but I'd expect that almost all of the performance hit you measured above (https://github.com/florimondmanca/djangorestframework-api-key/issues/173#issuecomment-1146677315) would be mitigated.

Performing a sha512 is very fast:

```
$ python -m timeit -s "import hashlib" "h=hashlib.sha512();h.digest()"
500000 loops, best of 5: 701 nsec per loop
```

You might still save the auth token model on the `request` if successful. For example, [django-rest-knox does that](https://github.com/James1345/django-rest-knox/blob/c48493d0fe99a20117110258c18944276addb7eb/knox/auth.py#L22-L34).

> * How to ensure hashes are properly migrated. Do we just switch the hasher, issue a new release and Django will magically upgrade hashes? Or do we need something else either from us, or from users with extra docs?

This will get a little tricky, I think. The `KeyGenerator` class probably needs to be changed. It needs to detect if the hash is in the old format and then call Django's `check_password`. If successful, it'll save it in the new format. `KeyGenerator` becomes something like this:

```python
from django.utils.crypto import constant_time_compare

class KeyGenerator:
    # ... other methods

    def hash(self, value: str) -> str:
        hash = hashlib.sha512(value.encode()).hexdigest()
        return "sha512$$%s" % hash

    def verify(self, key: str, hashed_key: str) -> bool:
        if hashed_key.startswith("sha512$$"):
            # New simpler hasher
            return constant_time_compare(self.hash(key), hashed_key)
        else:
            # Slower password hashers from Django
            result = check_password(key, hashed_key)
            if result:
                # UPDATE PASSWORD to use self.hash()
                # OR maybe we can pass custom `setter` option to `check_password`
                pass  
            return result
```

I considered a custom sha512 password hasher, but I don't think it actually does much. You can't use `check_password` since you can't pass a custom hasher there and since you can't add the hasher to Django's [`PASSWORD_HASHERS`](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-PASSWORD_HASHERS) setting because it's not appropriate as an actual password hasher. It does let you use `make_password` though:

```python
import hashlib
from django.contrib.auth.hashers import UnsaltedSHA1PasswordHasher, make_password

# The parent will be removed in Django 5.1
# so you probably don't want to rely on it.
class SHA512Hasher(UnsaltedSHA1PasswordHasher):
    algorithm = "sha512"
    digest = hashlib.sha512

    def encode(self, password, salt):
        if salt != "":
            raise ValueError("salt is unnecessary for high entropy API tokens.")
        hash = self.digest(password.encode()).hexdigest()
        return "%s$$%s" % (self.algorithm, hash)

encoded = make_password('mysecrets', hasher=SHA512Hasher())
```

At this stage, I feel like I'm writing a bunch of custom security critical code and getting many more eyes on this would be good before we go too far.

**Comment by florimondmanca** [comment]
Thanks @AlexIvanchyk 

Two questions from this

- Would it require action from users to set up caching if it hasn’t been set up already? Or is an in memory cache used by default?
- Perhaps the CACHING_TIMEOUT option should be retrieved from a setting by default, eg API_KEY_CACHING_TIMEOUT

I have a low amount of bandwidth to move things forward on this repo, but I’d be happy to review PRs if folks would like to put in the work to resolve this issue. I do think this would be a significant improvement.

**Comment by florimondmanca** [comment]
@AlexIvanchyk Hey, so coming back to this…

1. Great; so it doesn’t _require_ an intentional cache setup to work at least in degraded mode, which avoids any breaking change or heavy requirements for users. That’s perfect.
2. Yup, agreed with your proposed implementation of retrieving the setting.

Overall I think this is well thought out and a very beneficial change for all users.

We should be ready to move to implementation. Are you up for giving it a go? I don’t have much time to dedicated to the project in terms of new code developments, but I’ll be there for reviews.

**Comment by beda42** [comment]
Hi, I have just stumbled upon the performance issue as well.

From my point of view, the issue seems quite clear - the PBKDF2 and other password hashers are really not a good match for the task at hand. Switching to `sha2`, `sha3` or `blake2` hashing (something bundled with Python) should get rid of the whole problem without any drawback as already pointed out by @davidfischer. Caching the keys may sidestep part of the issue, but does feel like a potential source of security issues.

I would be willing to cooperate on making the switch to "normal" hashing possible. @davidfischer do you plan to create a PR? It seemed like you have something going a while ago...

**Comment by beda42** [comment]
> **Backward Compatibility:** Switching the hashing algorithm is an interesting suggestion but it introduces a backward compatibility issue. Existing applications using the current hashing mechanism would require migration, and this could be a non-trivial task for large-scale, distributed systems.

Well, as the key itself is not stored in the database, changing the hash for existing records is not possible unless a request containing the key is made. So the hashes will be updated on the fly and no migration will be required. Or the new hashing algorithm may be only used for new keys leaving the old ones completely untouched. Having this configurable via settings would probably be the best option.

> 
> **Security Concerns with Caching:** I appreciate your concern about security issues related to caching. However, it's important to note that we're caching the validation result (a boolean value), not the API key itself. This approach aims to balance performance and security. While no system can be 100% secure, this method minimizes the attack surface.
> 

The fact that only a boolean result of the validation is stored in the cache is exactly why it feels like a potential security problem to me. Normally only the database is the source of truth when it comes to authentication, but here a second source of truth is created and an attacker capable of modifying the cache can open access to the system. I am not sure if all developers pay the same attention to securing their redis cache as they do with their database.

Anyway, making this optional sounds like the best solution.

> **Multiple Permission Checks in DRF:** You're correct that using a less CPU-intensive hashing algorithm would improve performance. However, this doesn't address the issue of Django Rest Framework checking permissions multiple times per request, which is the crux of the performance bottleneck. Implementing caching would mitigate this problem more comprehensively, without requiring users to switch hashing algorithms and thereby lose backward compatibility.

My expectation of the performance after the hashing algorithm is changed, is to make the hashing faster than the database lookup for the key, which will effectively remove it from play. Please note that PBKDF2 is designed to be slow by repeatedly hashing the input - more than 200,000 times in current versions of Django - so the actual cost of hashing can be brought down by several orders of magnitude by using a plain hash instead of a "repeated" one. So this is not about changing one hash for another - it is about completely changing the method from a deliberately slow one to a super fast one.

So I would guess that if a simple hash it used, the caching will become effectively obsolete and it will have no measurable performance benefit.

**Comment by florimondmanca** [comment]
This discussion is extremely interesting, thank you everyone.

I’d like to note that I _think_ the current implementation makes use of Django’s password management helpers, which include a hash upgrade if the configured hasher changes.

I don’t remember if the hasher used is the one used for regular user passwords, or if PBKDF2 was used explicitly. One would need to dive into the code.

But this could reduce the migration burden for users if we go for a faster hash algorithm.

**Comment by beda42** [comment]
@AlexIvanchyk 

> In light of your valuable input, I propose a nuanced strategy that incorporates multiple solutions:
> 
>     1. Add an extra field to the key model indicating the hashing algorithm in use, with the default set to the current algorithm. This would allow dynamic algorithm selection during key validation. For keys using the older algorithm, we could update the hash in real-time after successful validation. `BLAKE2` seems to be the most suitable option. It's fast without compromising on security. My only concern is that users will need to do migrate command.
> 

The `hashed_key` field, which is currently populated by the Django password hashers, already has information about the used hasher. The format is `hash_algorithm$iterations$hashed_key`, so something like `pbkdf2_sha256$260000$OZ5OPvHiRZfIZ3nMBBAcZc$qjVVTR7vPwe3/9ifFfRk4zI+dH5yv…`. So we can easily identify the hasher which was used to create the hash to correctly check it. We could then adopt the same approach and store the new record like for example `blake2$$IZ3nMBBAcZc$qjVVTR7vPwe3/9ifFfRk4zI+dH5yv…`. This way, it would be possible to change the hashers during the lifetime of the app without any need for migration. In fact, this is how Django deals with hasher (and hasher parameter) changes when managing passwords (https://docs.djangoproject.com/en/3.2/topics/auth/passwords/#password-upgrading), so it is a tried and proven strategy.

BTW, @davidfischer already proposed a very good piece of code above which demonstrates exactly this approach.

As for hash algorithm selection, I also like BLAKE2, but ideally it should be configurable to give users an option while choosing a good default.

@AlexIvanchyk Do you plan working on this part of the task?

>     2. Provide an optional setting for caching, letting users with stringent security concerns disable this feature as needed.

Sounds good. Even though I would much more prefer to have it opt-in rather than opt-out - both because it is more prudent not to silently introduce stuff with potential security consequences, and because it relies on the cache which may be unexpected in an external library.

**Comment by beda42** [comment]
I have created a draft MR for the "plain" hash hashing. It is intended more as a starting point for discussion rather than complete solution. I would be happy for any feedback.

**Comment by florimondmanca** [comment]
Hey,

Sure, will do soon, keeping this on my todo list for when I have some time.

**Comment by davidfischer** [comment]
I created a PR (https://github.com/florimondmanca/djangorestframework-api-key/pull/244) for using faster hashers than the existing password hashers. It also transparently upgrades any old-format-hashes it finds in a similar way to what Django does.

**Comment by florimondmanca** [comment]
Given that #244 has been merged and will soon be released, I believe we can consider this issue closed for now.

Feedback will be gladly appreciated when 2.4.0 is out (in the coming days).

Big thanks to everyone involved. It's been a long due for sure, but a great final collaboration effort.
