### ISSUE TITLE
Auto-create API Key on users created

### ISSUE THREAD

**Issue by Oxyo78** [florimondmanca/djangorestframework-api-key#18]
Hello,
Thanks for this awesome package !
I would like to know if it's possible to auto-create the API key when a new user create an account ?

**Comment by florimondmanca** [comment]
Hi @Oxyo78 , thanks for the kind words!

I think this would be feasible using [Django's signals](https://docs.djangoproject.com/en/2.1/ref/signals) (especially `post_save`).

My concern is — if you create the API key programmatically, how would you communicate the secret key to the user? This is an honest question because maybe there are some missing helpers to support to use case.

**Comment by florimondmanca** [comment]
Also — be careful that this package was designed for service-to-service API keys. It wasn't meant to provide API keys to actual physical users (but again, the scope might be extended if we can clarify and document this need). :-)

**Comment by Oxyo78** [comment]
Thx for your feedback,
Actualy, I'm looking for an package to feed user API key to consume the API.
This can be a posibility :-)

**Comment by florimondmanca** [comment]
Yes, I see. I think this also requested in #16. If you're up for it, you can [open a feature request](https://github.com/florimondmanca/djangorestframework-api-key/issues/new?template=feature_request.md) to describe how you'd like this feature to work. :-) Formalising the need would help a lot.

**Comment by Oxyo78** [comment]
Sorry I didn't check the other post, I will check that :-)

**Comment by Oxyo78** [comment]
We can close this tread
