### ISSUE TITLE
Customization with Migration

### ISSUE THREAD

**Issue by maxillosoft-dimitry** [florimondmanca/djangorestframework-api-key#200]
I read the documentation and created similar customization such as:
# organizations/models.py
from django.db import models
from rest_framework_api_key.models import AbstractAPIKey

class Organization(models.Model):
    name = models.CharField(max_length=128)
    active = models.BooleanField(default=True)

class OrganizationAPIKey(AbstractAPIKey):
    organization = models.ForeignKey(
        Organization,
        on_delete=models.CASCADE,
        related_name="api_keys",
    )

class OrganizationAPIKey(AbstractAPIKey):
    some code specific to the project
    class Meta(AbstractAPIKey.Meta):
        verbose_name = "Organization API key"
        verbose_name_plural = "Organization API keys"

When I run ./manage.py migrate rest_framework_api_key, I thought it should only create the OrganizationAPIKey table but it also creates the rest_framework_api_key_apikey table in mysql.  On https://docs.djangoproject.com/en/2.2/topics/db/models/#abstract-base-classes, it says that abstract classes do not get created when class Meta: abstract = true and I see that in the AbstractAPIKey class.   

Any ideas what I am doing wrong?

Thanks
-Dimitry

**Comment by florimondmanca** [comment]
Hi @maxillosoft-dimitry, I believe this is related - if not a duplicate - of #180.

At the time:

* I summarized the use case here: https://github.com/florimondmanca/djangorestframework-api-key/issues/180#issuecomment-986258537
* There are notes on how to move this forward here: https://github.com/florimondmanca/djangorestframework-api-key/issues/180#issuecomment-986261324 and here: https://github.com/florimondmanca/djangorestframework-api-key/issues/180#issuecomment-986266208
* I started work on this branch: https://github.com/florimondmanca/djangorestframework-api-key/pull/191, which is on hold due to lack of time, but probably on the right path, and up to anyone taking it up.

Feel free to read through this issue and see if that corresponds to your use case. For now I am tentatively closing this. Thanks!
