### ISSUE TITLE
The use of PASSWORD_HASHERS should be documented more explicitly

### ISSUE THREAD

**Issue by sg2002** [florimondmanca/djangorestframework-api-key#22]
When trying to set up I could not get authorization working for quite a while. Then I noticed that this library uses PASSWORD_HASHERS for hashing. For a general case it would work, but people running custom setups like me, may run into issues. In my case I had BCryptPasswordHasher as the top choice and the authorization fails with it. PBKDF2PasswordHasher works fine. Haven't really tested the others. So may I suggest a small section in README about this, along with a list of supported hashers.

**Comment by florimondmanca** [comment]
Hey, thanks for reporting this.

I'm curious about why the bcrypt hasher doesn't work for you. Since we use the `default` hasher to hash the secret key (which means *all* Django hashers are supported), this should work, though I must say there isn't a test for this yet.

You mention `BCryptPasswordHasher` but [Using bcrypt with Django](https://docs.djangoproject.com/en/2.2/topics/auth/passwords/#using-bcrypt-with-django) indicates that `BCryptSHA256PasswordHasher` should be used instead. Can you try that out?
It would also be useful to see any relevant settings to be able to reproduce this; could you paste them here? :-)

Besides — we plan to remove the private `SECRET_KEY_ALGORITHM` setting and always use the `default` algorithm (i.e. the one configured in `PASSWORD_HASHERS`) as we currently do, see also #19. If that conflicts with your use case please let me know. :-)

**Comment by florimondmanca** [comment]
Hi @sg2002, I am going to close this issue for housekeeping purposes. As of 1.0 this package uses the default Django hasher and this has been documented in the README. Feel free to reopen if needed!

**Comment by tony** [comment]
@florimondmanca The issue is `BCryptPasswordHasher` won't work, and it's one of the `PASSWORD_HASHERS` django has in `django.contrib.auth.hashers.BCryptPasswordHasher`. It may be a good idea to [raise a warning](https://docs.djangoproject.com/en/2.2/topics/checks/) if this hasher is the top or the only hasher. _The package won't work with certain password hashers_.

I think @sg2002's recommendation of explicitly mentioning `BCryptPasswordHasher` works / doesn't work - or potentially a system to explicitly declare a hasher in settings for this plugin, would be more viable.

**Comment by tony** [comment]
It's possible for `make_password` to accept a hasher: https://docs.djangoproject.com/en/2.2/topics/auth/passwords/#django.contrib.auth.hashers.make_password

**Comment by florimondmanca** [comment]
Okay, got it. I wasn't aware using `PASSWORD_HASHERS` and some specific hashers would make this package fail. Has anybody got any traceback to share?

I think it's a good idea to allow to pass a `hasher` object directly, but how? I can hardly see this package not use the settings infrastructure (similarly to how user passwords gets the hasher from settings).

**Comment by tony** [comment]
@florimondmanca 

> I think it's a good idea to allow to pass a hasher object directly, but how? I can hardly see this package not use the settings infrastructure (similarly to how user passwords gets the hasher from settings).

I'm trying, but having issues.

```sh
                raise ValueError("Unknown password hashing algorithm '%s'. "
                                 "Did you specify it in the PASSWORD_HASHERS "
>                                "setting?" % algorithm)
E               ValueError: Unknown password hashing algorithm 'django.contrib.auth.hashers.BCryptSHA256PasswordHasher'. Did you specify it in the PASSWORD_HASHERS setting?
```

This is with:

```diff
-PASSWORD_HASHERS = ['django.contrib.auth.hashers.BCryptPasswordHasher']
+PASSWORD_HASHERS = [
+    'django.contrib.auth.hashers.BCryptPasswordHasher',
+    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',  # used by api keys
+]
```

(Note: I have djangorestframework-api-key vendorized / copied into my project)

```diff
+API_KEY_HASHER: str = 'django.contrib.auth.hashers.BCryptSHA256PasswordHasher'
+
+
 def generate_key() -> Tuple[str, str]:
+    from django.conf import settings
+
+    print(settings.PASSWORD_HASHERS)
     prefix = get_random_string(_PREFIX_LENGTH)
     secret_key = get_random_string(_SECRET_KEY_LENGTH)

     key = prefix + "." + secret_key  # for the client
-    key_id = prefix + "." + make_password(key)  # for database storage
+    key_id = (
+        prefix + "." + make_password(key, hasher=API_KEY_HASHER)
+    )  # for database storage

     return key, key_id


 def check_key(key: str, hashed_key: str) -> bool:
-    return check_password(key, hashed_key)
+    return check_password(key, hashed_key, preferred=API_KEY_HASHER)
```

For reference: https://docs.djangoproject.com/en/2.2/_modules/django/contrib/auth/hashers/#make_password

**Comment by tony** [comment]
@florimondmanca The `hasher` needs to be:

`'bcrypt_sha256'` instead of `'django.contrib.auth.hashers.BCryptSHA256PasswordHasher'`

> I think it's a good idea to allow to pass a hasher object directly, but how? I can hardly see this package not use the settings infrastructure (similarly to how user passwords gets the hasher from settings).

I feel django's way of adding `hasher` is a bit strange (since it's not immediately obvious to check for algorithm names, e.g. (`'pbkdf2_sha256'`, `'pbkdf2_sha1'`, `'argon2'`, `'bcrypt_sha256'`, `'bcrypt'`, `'sha1'`

But, that may be the most idiomatic option, if there was a setting:

```python
REST_FRAMEWORK_API_KEY_HASHER = 'bcrypt_sha256'
```

The user would still have to add the hasher to `PASSWORD_HASHERS`:

```python
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher'
]
````

**Comment by florimondmanca** [comment]
Thanks a lot for taking the time to figure things out, @tony. :+1:

> Edit: Unfortunately, I don't believe 'django.contrib.auth.hashers.BCryptSHA256PasswordHasher' ('bcrypt_sha256') can be relied upon either. It's generating periods in the output:

I think this is easy enough to fix: we're using `.split(".")`, but I think we could just as well use `.partition(".")` since we really just want to separate the hash before and after the first dot:

```python
prefix, _, hashed_key = api_key.key.partition(".")
```

That way, the hashing algorithm (e.g. bcrypts) can also use dots — we wouldn't care anymore.

Tbh, I'm having a hard time understanding why using the `"default"` hasher won't work. The Django source code seems to say that if we use `"default"`, it will use the first hasher in the `PASSWORD_HASHERS` list, which is what we want (although I agree that it needs to be better documented).

So I suspect this issue with `.split()` is the root cause of all this. @tony Can you check that the fix above allows you to use bcrypt?

**Comment by tony** [comment]
@florimondmanca Good point on [`str.partition()`](https://docs.python.org/3/library/stdtypes.html#str.partition)

This works with bcrypt for me. This is a nice solution (no need for custom hashers)

**Comment by florimondmanca** [comment]
Great! Wanna through a PR together for `str.partition()`? :-) I'll update the README afterwards.

**Comment by tony** [comment]
@florimondmanca Yeah, doing it now

**Comment by tony** [comment]
@florimondmanca #31

**Comment by florimondmanca** [comment]
I'll leave this open to track the necessary docs update. :+1:

**Comment by florimondmanca** [comment]
Released in 1.1 :+1: https://pypi.org/project/djangorestframework-api-key/1.1.0/

**Comment by tony** [comment]
Thank you @florimondmanca !

**Comment by sg2002** [comment]
Sorry, was really busy with other stuff, just want to pop in and say thanks to both of you guys for doing an amazing job in handling this issue.

**Comment by florimondmanca** [comment]
Thanks @sg2002! Appreciate the nice words. :-)
