### ISSUE TITLE
using name as service identifier

### ISSUE THREAD

**Issue by moezF** [florimondmanca/djangorestframework-api-key#69]
i am using 1.4.0
i have multiple services and i am restricting calls to some of them using api-key
let's say i have service A that will be consumed by many other services let's say just B and C
i am generating api-key for each B and C
the service A is doing some online automated payment tasks 

is it safe to use the api-key name to identify which request come from which service (as long as i am generating unique names) or i do have to do something like linking the API keys to an organisation

calls to service A are restricted by firewall only services B and C can access it
is it safe to remove this constraint as long as the generated key is kept secret ?

**Comment by florimondmanca** [comment]
Hey, thanks for this question!

In principle I don’t think there’s anything unsafe about using the name as a lightweight identification mechanism though — it’s more of a maintenance issue, because as I understand you’d potentially be hardcoding dynamic data into code for service A.

I’m not sure I understood the use case completely though — you clarify why you need to identify the service calling A in the first place?

As for the firewall bit, I can’t make the call for you but I would tend towards keeping it in place, and see API keys as a slight additional internal security measure.

**Comment by moezF** [comment]
thanks for your quick answer,
the maintenance point is interesting and i didn't think about it. i believe it won't be an issue since the service will behave the same independently from the name.

the service A do automated payments and it trusts all services that have api-key( and can pass the firewall rules), so i want to identify the consumer for each call to keep track of each transaction came from which service. this is for safety and tracking issues later. in case a service is doing something wrong or is infected it would be important to know which one

**Comment by florimondmanca** [comment]
Okay, I think I understand the use case better — for auditing purposes I believe it is fine to use the name for whichever logs you are going to create. You may just want to make sure the name isn’t editable (you can do this by customizing the APIKey admin), otherwise logs and existing keys may eventually fall out of sync.

I’m going to close this for now but if you have any more questions feel free to reopen/open another issue. :-)
