### ISSUE TITLE
Hashed passwords aren't migrated across Django versions

### ISSUE THREAD

**Issue by noslouch** [florimondmanca/djangorestframework-api-key#75]
When a hash is generated on one version of Django, it is not migrated when Django is upgraded.

According to the Django docs, salted passwords are [saved thusly](https://docs.djangoproject.com/en/2.1/topics/auth/passwords/#how-django-stores-passwords):
```
<algorithm>$<iterations>$<salt>$<hash>
```

As an aside, [the Django docs go on to mention](https://docs.djangoproject.com/en/2.1/topics/auth/passwords/#increasing-the-work-factor) (**emphasis added**):
>However, as computing power increases, the number of iterations needs to be increased. We’ve chosen a reasonable default **(and will increase it with each release of Django)**, but you may wish to tune it up or down, depending on your security needs and available processing power.

What does this mean? It means on Django 2.0.x, with the following token/secret key, you get the following hash from using [`hash_token`](https://github.com/florimondmanca/djangorestframework-api-key/blob/v0.4.0/rest_framework_api_key/permissions.py#L7):
```
token: 8efdf11c76ff3f7cacfc671a449eafce
secret: QAR37TDpiEeP
hashed token: pbkdf2_sha256$100000$QAR37TDpiEeP$nJSAj17/1ejl1FP4UjLPHouiuTLCcNd3m0z85mwhW2g=
```

On Django 2.1.x, with the same secret key/token, the following hash is generated:
```
pbkdf2_sha256$120000$QAR37TDpiEeP$NILHvaJbgM6MmvFFVQvEhJQR49L7LEhq4cnpx0TAOGg=
```

You can see the `<iterations>` segment changes between versions, which changes the resulting `<hash>`.

I'm currently on `v0.4.0`, and I see that the hashing logic has been rewritten for the newer versions. Does using `make_password` avoid this kind of issue? 

I'm willing to upgrade to `v1.x` and refactor my app, if this means DRFAK will handle migrating the hashes as Django increases the iterations it uses. Have you seen this issue come up in the past?

Django versions 2.0.x - 2.2.x
DRF versions 3.8.x - 3.9.x
DRF Api Key versions 0.3.x - 0.4.x

**Comment by florimondmanca** [comment]
Hey,

Thanks for opening this. Quite subtle!

I’m not sure what the expected behavior would be here — do we expect that the hash stored in the database somehow gets migrated when Django is upgraded? Or more generally, when password hashing settings change?

I don’t *think* this has been resolved in 1.x, but we’d need to check that this also occurs in 1.x. :)

Django has support for password upgrading, and I just found out that [check_password() accepts a `setter`](https://docs.djangoproject.com/en/2.1/_modules/django/contrib/auth/hashers/#check_password) parameter which is called when the password hash needs upgrade.

I think we could look at how to pass a callback that saves the new password on the API key object? That way, the hash will get upgraded next time the API key is used to authorize a request.

**Comment by noslouch** [comment]
Thanks for the response! I think we can close this as a non-issue for 1.x users and advise anyone on a pre-release version to upgrade. I've just verified locally that an api key generated on django 2.0.x continues to validate on 2.1.x and 2.2.x. 

I'm going to read through the source and run the generated key through whatever django core methods you're using just to triple check, but I'm feeling pretty confident that we can refactor our app, migrate our DB, and issue new keys as a permanent fix.

**Comment by florimondmanca** [comment]
Cool, thanks!
