### ISSUE TITLE
UserAPIKey set user if authorised

### ISSUE THREAD

**Issue by eikebartels** [florimondmanca/djangorestframework-api-key#95]
**Is your feature request related to a problem? Please describe.**
In my system, every user should be able to create api keys. Once the user uses this key, I would like to have the user object in the request as he would login via JWT, or token based. 

How could that work? I'm happy to implement it but I don't know what would be the best way. Any hits?

Cheers! And thanks for this awesome library

**Comment by florimondmanca** [comment]
Hi!

> Cheers! And thanks for this awesome library

Thanks for the kind words!

> Once the user uses this key, I would like to have the user object in the request as he would login via JWT, or token based.

So, I'm not sure I understand… the user would be provided *both* the API key, *and* authentication credentials, correct? If so, then doesn't the authentication scheme already populate `request.user` based on those credentials? I'm not sure what bit of API is missing here, actually.

**Comment by eikebartels** [comment]
Hey @florimondmanca thanks for the quick response. 

The User would either use the authentication credentials (web login) or the API key (third party like zapier). With normal credentials, Django attaches the user object to the request for later usage. For the API key auth that part is missing. Therefore we need to implement some kind of middleware for it I assum? 

Do you see my point? Any idea?

**Comment by florimondmanca** [comment]
Okay so, if I understand correctly, the endpoint at hand here is accessible via *either*:

- Authentication credentials. In that case the `request.user` is populated by the authentication backend, and there's no extra step required.
- An API key. In that case, you'd like to be able to access the associated user using `request.user`.

So, as documented in various places in the docs of this library, using API keys to identify users directly is not recommended, as it's too easy to shoot oneself in the foot and leak/expose/make sniffable user data that way. (Ideally the API key should be associated to specific resources that the API key gives access to, such as a `Project`, a `Dashboard`, etc.) So we won't be implementing it in core.

Would you mind taking a look at #93, though? If you do decide to link API keys to users, you would be able to use that to access a given `UserAPIKey` from a view, and from that access the `api_key.user`. You could then write your own middleware that sets `request.user` *for convenience* — making sure that permission classes were applied beforehand.

But again — if you have the possibility to retrieve the specific objects you want to operate on, rather than make a detour in users land, it's probably best. (I'm not fully aware of what happens once you've retrieved the user though, so I'll let that up to you to decide.)

**Comment by florimondmanca** [comment]
As far as the original question is concerned, I think we're good to close this as a "won't fix" for now. Feel free to continue discussion if you think there are extra items to work on besides what's proposed in #93. :-)

**Comment by eikebartels** [comment]
Hey @florimondmanca 

thanks again for your quick response and your explanation. 

It is actually very common to associate API key with a certain user. 
Good examples are https://id.atlassian.com/manage/api-tokens & https://github.com/settings/tokens/new 

I guess the reason is, that you as a user should take the responsibility for creating one. 
In additional to that, the permission of a user is most likely already deep and all over the code base in all project. So to create a fine grand permission for an API key, associating the API with a user make sense. Even if you create a specify user only for the key. 


I saw #93 and actually took it already to try it out. Works like a charm.

**Comment by florimondmanca** [comment]
Oh, sure, it's probably a rather common pattern from a user point of view to be told "hey, here's *your* API key". I just don't want this package to make any recommendation that might in the end result in potential security issues because of bad practices. :-) So, yup, the policy is really just "you can do it, but at your own risks". Hence all the warnings flags about "this is not meant for authentication" — although you could very much end up using it for that, *if that's what you consciously decide to do*…

**Comment by eikebartels** [comment]
Yea I see your point and it makes totally sense! :) 

Ill create a "extension" package for `djangorestframework-api-key` which covers this case. 

Different topic but related to my case, it would be cool to restrict the API key to a certain domain.

**Comment by florimondmanca** [comment]
> restrict the API key to a certain domain

As in, allow e.g. "you can use these API keys to access `app.mysite.com`, but not `shop.mysite.com`"? That's a pretty neat feature idea, yup. Can probably be implemented as a custom base permission class/mixin, and probably hooking up into Django's sites frameworks… If you're already investigating that, let me know if there's any extension API we'd be missing in core to make that possible.

**Comment by eikebartels** [comment]
>As in, allow e.g. "you can use these API keys to access app.mysite.com, but not shop.mysite.com"?

I more mean, you can use this API key to access the page/ Rest API when your ip is.... like whitelisting IPs for using this key.

**Comment by florimondmanca** [comment]
Ah, I see. That can definitely be useful as a mitigation means as well, e.g. against DoS attacks and we don't want to revoke the API key just yet… Would probably need both a safelist and a blocklist mechanism to cover all use cases.

One could even imagine other of ways of restricting usage, e.g. filtering based on `Referrer`, mobile app, requested endpoint, … And that also leads to rate limiting/throttling, etc. That's a whole range of possible new features. :-) Folks using this package are probably encountering these use cases in the wild, so I'd be excited to see any third-party package focusing on that area of things.

**Comment by ekerstein** [comment]
@eikebartels just came across this thread and wanted to check in and see if you came across a good solution to whitelisting IP addresses for user API keys.

Your use case sounds like exactly what I'm also looking for: allow users to create API keys associated with their account, and restrict that API access to a specific inputted IP address. ￼

**Comment by eikebartels** [comment]
Hey @ekerstein sorry I did not invest more into this but it should work like this:

1. Create a custom model and add ip Field 

```
class UserAPIKey(AbstractAPIKey):
    class Meta(AbstractAPIKey.Meta):
        verbose_name = "User API key"
        verbose_name_plural = "User API keys"

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="api_keys",)
    ip = models.IPAddressField()
```

2. Use custom middleware 

```
class ApiKeyAuthentication(authentication.BaseAuthentication):
    """
    An authentication plugin that authenticates requests through a API key provided in a request header.

    """

    def authenticate(self, request):
        validator = HasUserAPIKey()
        key = validator.get_key(request)

        if not key:
            return None

        try:
            user_api_key = validator.model.objects.get_from_key(key)
        except ObjectDoesNotExist:
            return None

        request_ip = request.META.get("REMOTE_ADDR")

        if request_ip != user_api_key.ip:
            return None

        try:
            user = User.objects.get(pk=user_api_key.user_id)
        except User.DoesNotExist:
            return None

        if not user.is_active:
            return None

        if not get_thread_variable("user_id"):
            set_thread_variable("user_id", user.id)

        return user, None

    def authenticate_header(self, request):
        return 'Bearer realm="api"'
```

3. Register middleware 

```
REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "core.utils.exceptions.rest_exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "core.authentication.JWTAuthentication",
        "core.authentication.ApiKeyAuthentication",
    ),
```

To get the API from the request see https://docs.djangoproject.com/en/2.2/ref/request-response/#django.http.HttpRequest.META

**Comment by eikebartels** [comment]
Ah sorry @ekerstein I didn't read your post carefully enough... Ill get my previous comment anyway. 

> I'm thinking it would involve creating a whitelist model associated with the API key. Then creating a new permission class to check if the API key and remote_addr header match up. Similar to what's discussed here: https://stackoverflow.com/questions/59309342/drf-how-do-i-whitelist-a-site-for-endpoint-requests

Yes you have to create your own model. As I did in my post above. To whitelist more than one Ip you could also create a one to  many relationship. 

I think it is straight forward.

**Comment by ekerstein** [comment]
Thank you @eikebartels I really appreciate it. I've been slowly working through your code and had three questions:

1. I extended the BaseHasAPIKey permissions class to make my own HasUserAPIKey permissions. I assume that's what you're referencing at the beginning of the authentication middleware. My question is, in the API view do I need to reference both? My intuition is no, because the authentication seems to already be checking the permissions (if the key is expired or revoked) but want to make sure I understand the logic. 
```
# Do I need both?
authentication_classes = [UserAPIKeyAuthentication]
permission_classes = [HasUserAPIKey]
```
2.  Can you explain what this does in the authentication?
```
if not get_thread_variable("user_id"):
     set_thread_variable("user_id", user.id)
```
3. I noticed you're returning None at each step of the authentication. Shouldn't this be raising this an error so the user gets a 401? For example, instead of this:

```
if not key:
     return None
```
Shouldn't it be this?
```
if not key:
     raise AuthenticationFailed('No API key provided.')
```

Thank you! Still new to all this.

**Comment by eikebartels** [comment]
Hey @ekerstein 


> 1. Can you explain what this does in the authentication?
> 
> ```
> if not get_thread_variable("user_id"):
>      set_thread_variable("user_id", user.id)
> ```

Oh yea this is actually a custom implementation on my side. You do not need it. I'm using it for logging purposes. Just as a reference, here my implementation

```
"""
A module for storing global data. Use with care.
Thread local variables are similar to global variables, but their scope is limited to the thread of execution.
"""
from threading import local

_threadlocals = local()


def set_thread_variable(key, val):
    setattr(_threadlocals, key, val)


def get_thread_variable(key, default=None):
    return getattr(_threadlocals, key, default)


def clear_threadlocals():
    global _threadlocals
    _threadlocals = local()

```

> 1. I noticed you're returning None at each step of the authentication. Shouldn't you be raising an error so the user gets a 401? For example, instead of this:
> 
> ```
> if not key:
>      return None
> ```
> 
> Shouldn't it be this?
> 
> ```
> if not key:
>      raise AuthenticationFailed('No API key provided.')
> ```

No, not in my case at least. I'm using the DRF 
<img width="604" alt="image" src="https://user-images.githubusercontent.com/767979/92446869-c7ffe680-f1b6-11ea-9f7b-ca79bf859fae.png">

which defines the request if the `authenticate` method does not return a user object. Most likely `raise AuthenticationFailed('No API key provided.')` will also work. I didn't try it.
